/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)
[info] Parsing spec ...
[info] Parsing succeeded
[info] Building synthesizer ...
[info] Synthesizing programs ...
[info] # candidates before getting the correct solution: 0
[info] Solution found: gather(@param0, ['2', '3', '4'])
[info] Parsing spec ...
[info] Parsing succeeded
[info] Building synthesizer ...
[info] Synthesizing programs ...
[info] Solution not found!
[info] Synthesizing programs ...
====> run synthesize test_18.json
# num samples per layer: 4
   label    y0    y1    y2   ...    int x3  int y1  int y2  int y3
0    1.0  50.0  46.0  14.0   ...      0.00   46.34   42.30   78.00
1    2.0  82.0  43.0  37.0   ...      0.00    9.00   39.57   50.50
2    3.0  54.0  27.0  49.0   ...      0.00   81.93   43.64   50.93
3    4.0  84.0  86.0  30.0   ...     26.51   58.66   44.25   44.53
4    5.0   8.0   4.0  58.0   ...      0.00   11.33   72.86  103.23
5    6.0  48.0  92.0  77.0   ...     28.85   62.48   74.81   71.02
6    7.0  75.0  37.0  70.0   ...      0.00   84.50   13.42   75.45
7    8.0  74.0  32.0  58.0   ...      0.00    0.00    0.00    0.00

[8 rows x 10 columns]
  c_color  c_x   c_y
0      y1  2.0  43.0
1      y1  7.0  37.0
2      y2  7.0  70.0
3      y0  8.0  74.0
# candidates before getting the correct solution: 0
   label    y0    y1    y2   ...    int x3  int y1  int y2  int y3
0    1.0  50.0  46.0  14.0   ...      0.00   46.34   42.30   78.00
1    2.0  82.0  43.0  37.0   ...      0.00    9.00   39.57   50.50
2    3.0  54.0  27.0  49.0   ...      0.00   81.93   43.64   50.93
3    4.0  84.0  86.0  30.0   ...     26.51   58.66   44.25   44.53
4    5.0   8.0   4.0  58.0   ...      0.00   11.33   72.86  103.23
5    6.0  48.0  92.0  77.0   ...     28.85   62.48   74.81   71.02
6    7.0  75.0  37.0  70.0   ...      0.00   84.50   13.42   75.45
7    8.0  74.0  32.0  58.0   ...      0.00    0.00    0.00    0.00

[8 rows x 10 columns]
   c_x    c_y c_color
0  7.0   0.00  int x3
1  2.0   9.00  int y1
2  7.0  84.50  int y1
3  6.0  74.81  int y2
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF25675 <- RET_DF25673 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF25684 <- RET_DF25682 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF25824 <- RET_DF25822 %>% mutate(cumsum=cumsum(.[[2]]))',)
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF27889 <- RET_DF27887 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF27892 <- RET_DF27890 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF27895 <- RET_DF27893 %>% mutate(cumsum=cumsum(.[[2]]))',)
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF28980 <- RET_DF28978 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF29005 <- RET_DF29003 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in synthesize
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 87, in <listcomp>
    layer_candidate_progs = [morpheus.synthesize(inputs, p[0], p[1], prune, extra_consts=extra_consts) for p in sym_tables]
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF29008 <- RET_DF29006 %>% mutate(cumsum=cumsum(.[[1]]))',)
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...

real	10m0.069s
user	9m36.742s
sys	0m13.640s
